### ISSUE TITLE
video can not be opened

### ISSUE THREAD

**Issue by leeqiaogithub** [yalesong/thumbnail#4]
I opened the video according to video_url,but all video can not be opened,why?

**Comment by yalesong** [comment]
It's probably because the videos are no longer available on Yahoo websites. Send me your email address so that we can find an alternative solution.

**Comment by leeqiaogithub** [comment]
Thanks for your reply! I wonder Whether these videos have zone limit.Because when I changed the export to Hong Kong, some videos could play.

**Comment by yalesong** [comment]
I don't know about the zone limit setting for those videos, but it's certainly possible. I am no longer at Yahoo Research and have no way to verify that.

**Comment by leeqiaogithub** [comment]
ok,thank you so much anyway.
