### ISSUE TITLE
application for dataset again~

### ISSUE THREAD

**Issue by Liquor520** [yalesong/thumbnail#7]
Hello, I also wanted to reproduce your results recently, but I could not get the data set. Would you mind providing me them. I would be most appreciative if you could. Thank you in advance.

**Comment by yalesong** [comment]
Could you please contact me directly via email? You can check my contact info on my website. Thanks!

**Comment by Liquor520** [comment]
I have contacted you through email ~ hope to receive your reply ~

**Comment by yalesong** [comment]
For some reason I don't see it (I checked spam folders). If you could just give me your email address I will contact you separately.

**Comment by Liquor520** [comment]
1481663704@qq.com
thank you very much!!!!
